server:
  port: 8091

spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/itstyle/
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 1000MB

ftp:
  host: 127.0.0.1
  port: 21
  username: root
  password: 123456